sudo: required

services:
  - docker

install:
  - docker build -t libreconv .
  - docker run -d -p 8080:8080 libreconv

script:
  - curl -XPOST -F "file=@./testdata/example.docx" "http://localhost:8080/to/pdf?timeout=10s" -o /dev/null -v